import time
from pathlib import Path
from typing import List, Dict, Any
from jinja2 import Environment, FileSystemLoader
from src.config import AppConfig

# Base Directory
BASE_DIR = Path(__file__).resolve().parent.parent

class ReportFormatter:
    """Renders analyzed repositories into aesthetic Markdown, Feishu, and Slack reports."""
    
    def __init__(self, config: AppConfig, persona: Dict[str, Any], timeframe: str):
        self.config = config
        self.persona = persona
        self.timeframe = timeframe
        self.timestamp = time.strftime("%Y-%m-%d %H:%M")
        
        # Initialize Jinja2 environment
        template_dir = BASE_DIR / "templates"
        if template_dir.exists():
            self.env = Environment(loader=FileSystemLoader(str(template_dir)))
        else:
            self.env = None
            print("[Formatter Warning] Templates directory not found. Using fallbacks.")

    def generate_all(self, repos: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Generates all report formats."""
        total_input = self.config.github.max_trending_repos
        
        context = {
            "repos": repos,
            "persona": self.persona,
            "timeframe": self.timeframe,
            "timestamp": self.timestamp,
            "total_input": total_input,
            "model_v3": self.config.ai.model_v3,
            "model_r1": self.config.ai.model_r1
        }
        
        markdown_report = self._render_template("report.md.j2", context, self._fallback_markdown(repos))
        feishu_payload = self._render_json_template("feishu_card.json.j2", context, self._fallback_feishu(repos))
        slack_payload = self._render_json_template("slack_blocks.json.j2", context, self._fallback_slack(repos))
        
        return {
            "markdown": markdown_report,
            "feishu": feishu_payload,
            "slack": slack_payload
        }

    def _render_template(self, template_name: str, context: Dict[str, Any], fallback: str) -> str:
        """Renders a Jinja2 template with fallback support."""
        if not self.env:
            return fallback
            
        try:
            template = self.env.get_template(template_name)
            return template.render(**context)
        except Exception as e:
            print(f"[Formatter Warning] Failed to render {template_name}: {e}. Using fallback.")
            return fallback

    def _render_json_template(self, template_name: str, context: Dict[str, Any], fallback: Dict[str, Any]) -> Dict[str, Any]:
        """Renders a Jinja2 template and parses it as a JSON object, with fallback support."""
        if not self.env:
            return fallback
            
        try:
            template = self.env.get_template(template_name)
            rendered = template.render(**context)
            # Remove any trailing commas that J2 loops might have generated
            # and clean up whitespaces
            return json.loads(rendered)
        except Exception as e:
            print(f"[Formatter Warning] Failed to render or parse JSON {template_name}: {e}. Using fallback.")
            return fallback

    def _fallback_markdown(self, repos: List[Dict[str, Any]]) -> str:
        """Generates a simple, robust fallback markdown string if Jinja rendering fails."""
        lines = [
            f"# 🌌 GitHub 开源趋势 & LLM 大厂动态周报 (Fallback)",
            f"> **画像**: {self.persona['name']} | **时间**: {self.timestamp}\n",
            "---",
            "## 📊 精选列表\n"
        ]
        
        for r in repos:
            lines.append(f"### [{r.get('rating', 'B')}] {r['full_name']}")
            lines.append(f"- **URL**: {r['url']}")
            lines.append(f"- **Tags**: {', '.join(r.get('tags', []))}")
            lines.append(f"- **Description**: {r['description']}\n")
            lines.append(r.get('chinese_summary', r.get('refined_summary', '')))
            lines.append("\n---\n")
            
        lines.append("\n*Generated by auto_github fallback system.*")
        return "\n".join(lines)

    def _fallback_feishu(self, repos: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Generates a basic fallback Feishu Interactive Card message."""
        elements = [
            {
                "tag": "markdown",
                "content": f"**🌌 GitHub Trend Report ({self.persona['name']})**\nTimestamp: {self.timestamp}"
            },
            {"tag": "hr"}
        ]
        
        for r in repos[:5]: # Top 5 to fit Feishu card limits
            elements.append({
                "tag": "div",
                "text": {
                  "tag": "lark_md",
                  "content": f"**[{r.get('rating', 'B')}] {r['full_name']}**\nTags: {', '.join(r.get('tags', []))}\n\n{r.get('chinese_summary', '')[:500]}"
                },
                "extra": {
                  "tag": "button",
                  "text": {"tag": "plain_text", "content": "Open GitHub"},
                  "type": "primary",
                  "url": r["url"]
                }
            })
            elements.append({"tag": "hr"})
            
        return {
            "msg_type": "interactive",
            "card": {
                "config": {"wide_screen_mode": True},
                "header": {
                    "template": "blue",
                    "title": {"tag": "plain_text", "content": "GitHub Trending Fallback"}
                },
                "elements": elements
            }
        }

    def _fallback_slack(self, repos: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Generates a basic fallback Slack message payload."""
        blocks = [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": f"GitHub Trend Report ({self.persona['name']})",
                    "emoji": True
                }
            }
        ]
        for r in repos[:5]:
            blocks.append({
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*<{r['url']}|{r['full_name']}>* | Rating: `{r.get('rating', 'B')}`\n{r.get('chinese_summary', '')[:300]}..."
                }
            })
        return {"blocks": blocks}

# Ensure json is imported
import json
